/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_redknot_julia_JuliaJNI */

#ifndef _Included_com_redknot_julia_JuliaJNI
#define _Included_com_redknot_julia_JuliaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_redknot_julia_JuliaJNI
 * Method:    CreateJulia
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_redknot_julia_JuliaJNI_CreateJulia
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_redknot_julia_JuliaJNI
 * Method:    CreateOnFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_redknot_julia_JuliaJNI_CreateOnFrame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
